import asyncio
import json
import os
import sys

# Add current directory to path
sys.path.insert(0, os.getcwd())

from text_gen_parser import TextGenParser

async def test_lider_full():
    parser = TextGenParser()
    message = """🚚LİDER NAKLİYAT 🚚

81 İL VE İLÇEYE KAPALI TENTEN 
TERMOKİN YÜKLEMEM VAR.  

05521025624☎️

KIZILTEPE ANTEP MERKEZ 
KIZILTEPE MARAŞ MERKEZ 
KIZILTEPE HATAY MERKEZ
KIZILTEPE MERSİN MERKEZ 
KIZILTEPE ADANA MERKEZ 
KIZILTEPE İSKENDERUN MERKEZ 
KIZILTEPE İSKENDERUN ARSUZ 
KIZILTEPE OSMANİYE KADİRLİ 
KIZILTEPE MARAŞ MERKEZ
KIZILTEPE DÜZCE MERKSZ
KIZILTEPE ADAPAZARI MERKEZ 
KIZILTEPE İZMİT MERKEZ 
KIZILTEPE İSTANBUL HABİPLER 
KIZILTEPE GEBZE MERKEZ 
KIZILTEPE MANİSA MERKEZ
KIZILTEPE MANİSA KULA 
KIZILTEPE MANİSA AKHİSAR 
KIZILTEPE İZMİR TORBALI 
KIZILTEPE İZMIR MENDERES 
KIZILTEPE MANİSA SALIHLI 
KIZILTEPE ANKARA ÇUBUK 
KIZILTEPE ANKARA MERKEZ 
KIZILTEPE KONYA EREĞLİ 
KIZILTEPE KONYA MERKEZ 
KIZILTEPE KONYA CIHANBEYLI 
KIZILTEPE KONYA KULU 
KIZILTEPE BURDUR MERKEZ
KIZILTEPE ANTALYA MERKEZ 
KIZILTEPE ALANYA MERKEZ 
KIZILTEPE DENİZLİ MERKEZ
KIZILTEPE AYDIN NAZILI 
KIZILTEPE UŞAK EŞME 
KIZILTEPE NİĞDE MERKEZ 
KIZILTEPE BURSA MERKEZ 
KIZILTEPE BALIEKSİR MERKEZ 
KIZILTEPE AFYON MERKEZ 
KIZILTEPE AFYON EMRİDAĞ 
KIZILTEPE AFYON ÇAY 
KIZILTEPE ANTALYA MANAVGAT 
KIZILTEPE BURDUR ÇAVDIR 
KIZILTEPE KONYA ÇUMRA
KIZILTEPE BURSA YENİŞEHİR 
KIZILTEPE ANKARA KULU  
KIZILTEPE AYDIN SÖKE 
KIZILTEPE ANTALYA KORKUTELİ 
KIZILTEPE MERSİN MUT 
KIZILTEPE İSTANBUL ARNAVUTKÖY 
KIZILTEPE MALATYA MERKEZ 
KIZILTEPE MERSİN GÜLNAR 
KIZILTEPE İZMİR ÖDEMİŞ 
KIZILTEPE İZMIR KİRAZ 
KIZILTEPE ANTALYA KUMLUCA 
KIZILTEPE ESKIŞEHIR MERKEZ 
KIZILTEPE ESKIŞEHIR MAHMUDİYE 
KIZILTEPE BURSA KESTEL 
KIZILTEPE BURSA YENİŞEHİR 
KIZILTEPE ESKIŞEHIR ÇİFTELER
KIZILTEPE MARAŞ ILICA 
KIZILTEPE AFYON ŞUHUT 
KIZILTEPE BOLU MEKREZ 
KIZILTEPE ANKARA KIZILCIHAMAM 
KIZILTEPE ANKARA SİNCAN 
KIZILTEPE BİLECİK MERKEZ 
KIZILTEPE BALIEKSİR İVRİNDİ 
KIZILTEPE İSTANBUL TEKİRDAĞ 
KIZILTEPE ISPARTA MERKEZ 
KIZILTEPE İSTANBUL SULTANBEYLİ 
KIZILTEPE ORDU MERKEZ 
KIZILTEPE SAMSUN MERKEZ 
KIZILTEPE ZONGULDAK MERKEZ 
KIZILTEPE MANİSA GÖLMARMARA 
KIZILTEPE ALANYA GAZİPAŞA 
KIZILTEPE KAYSERİ MERKEZ 
KIZILTEPE İSTANBUL FERHATPAŞA 
KIZILTEPE İSTANBUL BAŞAKŞEHİR 
KIZILTEPE SAMSUN MERKEZ 
KIZILTEPE MALATYA MERKEZ 
KIZILTEPE ORDU MERKEZ 
KIZILTEPE SAMSUN ÇARŞAMBA

81 İL VE İLEÇEYE KAPALI TENTEN 
TERMOKİN YÜKLEMELERİMİZ VAR.  

05521025624☎️

🚚LİDER NAKLİYAT🚚"""

    print("Parsing full message...")
    results = await parser.parse_async(message)
    
    print(f"\nPARSED {len(results)} RESULTS.")
    
    with open('scratch/lider_full_debug.json', 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

if __name__ == "__main__":
    asyncio.run(test_lider_full())
